const LOAD_SIDEBAR_STATUS = 'sidebar/LOAD_SIDEBAR_STATUS'
const LOAD_SIDEBAR_STATUS_SUCCESS = 'sidebar/LOAD_SIDEBAR_STATUS'
const LOAD_SIDEBAR_STATUS_FAIL = 'sidebar/LOAD_SIDEBAR_STATUS_FAIL'
const STORE_SIDEBAR_STATUS = 'sidebar/STORE_SIDEBAR_STATUS'
const CLEAR_STORE = 'sidebar/CLEAR_STORE'

export default {
  LOAD_SIDEBAR_STATUS,
  LOAD_SIDEBAR_STATUS_SUCCESS,
  LOAD_SIDEBAR_STATUS_FAIL,
  STORE_SIDEBAR_STATUS,
  CLEAR_STORE,
}
