const LOAD_COMMENT = 'comment/LOAD_COMMENT'
const LOAD_COMMENT_SUCCESS = 'comment/LOAD_COMMENT_SUCCESS'
const LOAD_COMMENT_FAIL = 'comment/LOAD_COMMENT_FAIL'
const STORE_COMMENTS = 'comment/STORE_COMMENTS'

export default {
  LOAD_COMMENT,
  LOAD_COMMENT_SUCCESS,
  LOAD_COMMENT_FAIL,
  STORE_COMMENTS,
}
