const LOAD_COMMENT = 'comment/LOAD_COMMENT'
const LOAD_COMMENT_SUCCESS = 'comment/LOAD_COMMENT_SUCCESS'
const LOAD_COMMENT_FAIL = 'comment/LOAD_COMMENT_FAIL'
const STORE_COMMENTS = 'comment/STORE_COMMENTS'
const ADD_COMMENT = 'comment/ADD_COMMENT'
const DELETE_COMMENT = 'comment/DELETE_COMMENT'
const EDIT_COMMENT = 'comment/EDIT_COMMENT'
export default {
  LOAD_COMMENT,
  LOAD_COMMENT_SUCCESS,
  LOAD_COMMENT_FAIL,
  ADD_COMMENT,
  DELETE_COMMENT,
  EDIT_COMMENT,
  STORE_COMMENTS,
}
